---
title: "portfolio2"
author: "Juli Furjes"
date: "2024-02-22"
output: pdf_document
---

```{r installing}
pacman::p_load(tidyverse,
               here,
               posterior,
               cmdstanr,
               brms, 
               tidybayes, 
               loo)
```


```{r compiling model}
# Compiling model
portfolio2_model <- cmdstan_model("portfolio2_alternative.stan", cpp_options = list(stan_threads = TRUE), pedantic = TRUE)

#portfolio2_model.fromFile$exe_file() # Show location of executable
```

```{r simulation}
# Create a function to introduce noise and rate
RandomAgentNoise_f <- function(rate, noise) {
  choice <- rbinom(1, 1, inv_logit_scaled(rate)) # generating noiseless choices
  if (rbinom(1, 1, noise) == 1) {
    choice <- rbinom(1, 1, 0.5) # introducing noise
  }
  return(choice)
}

# Create a function that checks if choice was successful
WinLoseSuccess_f <- function(choice, hand) {
  choice <- as.integer(choice)
  hand <- as.integer(hand)
  if (choice == hand) {
    feedback <- 1
  } else {
    feedback <- 0
  }
  return(feedback)
}

# Create a function that generates the choices
WinLoseResults_model_f <- function(trials, noise, rate, betagamble) {
  feedback <- numeric(trials)
  choice <- numeric(trials)
  hand <- numeric(trials)
  gamble <- numeric(trials)
  # logit_rate <- logit_scaled(rate)
  for(i in 1:trials) {
    hand[i] <- rbinom(1, 1, 0.5)
    if (i>=3) {
      if (choice[i-1] == choice[i-2] & feedback[i-1] == 1 & feedback[i-2] == 1) {
          gamble[i] <- (1-2*choice[i-1])
          choice[i] <- rbinom(1,1,inv_logit_scaled(rate+betagamble*gamble[i])) # If both of them were success, switch
        } else if (choice[i-1] == choice[i-2] & feedback[i-1] == 0 & feedback[i-2] == 0) {
          gamble[i] <- (-1+2*choice[i-1])
          choice[i] <- rbinom(1,1,inv_logit_scaled(rate+betagamble*gamble[i])) # If both of them were fail, stay
        } else { # If feedback changed
          choice[i] <- RandomAgentNoise_f(rate, noise) # Randomly generate based on rate and noise
        }
    } else { # If it hasn't been 3 trials yet
        choice[i] <- RandomAgentNoise_f(rate, noise) # Randomly generate based on rate and noise
    }
    feedback[i] <- WinLoseSuccess_f(choice[i], hand[i])
  }
  return(list(choice = choice, feedback = feedback, hand = hand, gamble = gamble))
}
```

```{r noise and rate}
# Amount of trials
trials <- 120

# Play around with noise, rate, and betagamble levels
# Initialize empty tibble
d <- tibble(trial = integer(), choice = double(), rate = double(), noise = double(), cumulativerate = double())

# Initialize choice vector
choices <- rep(NA, trials)

for (noise in seq(0, 0.5, 0.1)) { # Looping through noise levels
  for (rate in c(-5,-3,-1,-0.5,0,0.5,1,3,5)) { # Looping through rate levels
    for (beta_g in c(-10,-5,-1,-0.5,0,0.5,1,5,10)) {
      results <- WinLoseResults_model_f(trials, noise, rate, beta_g)
      # results <- WinLoseResults_f(trials, noise, rate)
        
      temp <- tibble(trial = seq(trials), choice = results$choice, rate = rate, noise = noise, betagamble = beta_g, gamble = results$gamble)
      temp$cumulativerate <- cumsum(temp$choice) / seq_along(temp$choice)
  
      d <- rbind(d, temp)
    }
  }
}

# p1 <- ggplot(d, aes(trial, cumulativerate, group = rate, color = rate)) + 
#   geom_line() + 
#   geom_hline(yintercept = 0.5, linetype = "dashed") + 
#   ylim(0,1) + 
#   facet_wrap(.~noise) + 
#   theme_classic()

p1 <- d %>% 
  ggplot(aes(trial, cumulativerate, group = rate, color = rate)) + 
    geom_line() + 
    geom_hline(yintercept = 0.5, linetype = "dashed") + 
    ylim(0,1) + 
    facet_grid(vars(noise), vars(betagamble)) + 
    theme_classic()

p1
```

```{r data}
# Set up data
trials <- 120

# Generate list of choices
noise <- 0
rate <- 1
betagamble <- -1.5
outcome <- WinLoseResults_model_f(trials, noise, rate, betagamble)

# Create the data
data <- list(
  trials = trials,
  success =  outcome$feedback,
  # hand = outcome$hand,
  choice = outcome$choice
)
```

```{r modeling, message=FALSE, warning=FALSE}
samples <- portfolio2_model$sample(
   data = data,
   seed = 123,
   chains = 2,
   parallel_chains = 2,
   threads_per_chain = 2,
   iter_warmup = 2000,
   iter_sampling = 2000,
   refresh = 500,
   max_treedepth = 20,
   adapt_delta = 0.99,
)
```


```{r summary}
# Summary

samples$summary()
```

```{r visualisations}
# Visualisations for prior posterior updates

# Extract posterior samples and include sampling of the prior:
draws_df <- as_draws_df(samples$draws())

# Now let's plot the density for theta (prior and posterior)
prior_plot_1 <- ggplot(draws_df) +
  geom_density(aes(inv_logit_scaled(rate)), fill = "blue", alpha = 0.3) +
  geom_density(aes(inv_logit_scaled(rate_prior)), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = inv_logit_scaled(rate)) +
  xlab("Rate (Probability Space)") +
  ylab("Estimate Densities") +
  theme_classic() +
  labs(title = "Prior and Posterior Distrbution for Rate", subtitle = "Black line indicates true value")

prior_plot_2 <- ggplot(draws_df) +
  geom_density(aes(rate), fill = "blue", alpha = 0.3) +
  geom_density(aes(rate_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = rate) +
  xlab("Rate (Log space)") +
  ylab("Estimate Densities") +
  theme_classic() +
  labs(title = "Prior and Posterior Distrbution for Rate", subtitle = "Black line indicates true value")

prior_plot_3 <- ggplot(draws_df) +
  geom_density(aes(inv_logit_scaled(betaGamble)), fill = "blue", alpha = 0.3) +
  geom_density(aes(inv_logit_scaled(betaGamble_prior)), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = inv_logit_scaled(betagamble)) +
  xlab("Beta Gamble (Probability Space)") +
  ylab("Estimate Densities") +
  theme_classic() +
  labs(title = "Prior and Posterior Distrbution for BetaGamble", subtitle = "Black line indicates true value")

prior_plot_4 <- ggplot(draws_df) +
  geom_density(aes(betaGamble), fill = "blue", alpha = 0.3) +
  geom_density(aes(betaGamble_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = betagamble) +
  xlab("Beta Gamble (Log space)") +
  ylab("Estimate Densities") +
  theme_classic() +
  labs(title = "Prior and Posterior Distrbution for BetaGamble", subtitle = "Black line indicates true value")

# ggplot(draws_df) +
#   geom_density(aes(rate_prior), fill = "blue", alpha = 0.3) +
#   #geom_density(aes(betaGamble_prior), fill = "red", alpha = 0.3) +
#   #geom_vline(xintercept = betagamble) +
#   #xlab("Beta Gamble") +
#   ylab("Posterior Density") +
#   theme_classic() +
#   lims(x = c(-2.5,2.5))
# 
# ggplot(draws_df) +
#   geom_density(aes(betaGamble_prior), fill = "blue", alpha = 0.3) +
#   #geom_density(aes(betaGamble_prior), fill = "red", alpha = 0.3) +
#   #geom_vline(xintercept = betagamble) +
#   #xlab("Beta Gamble") +
#   ylab("Posterior Density") +
#   theme_classic()  +
#   lims(x = c(-2.5,2.5))

prior_plot_1
prior_plot_2
prior_plot_3
prior_plot_4

ggsave(filename = "figures/prior_plot_rate.png", plot = prior_plot_1)
ggsave(filename = "figures/prior_plot_rate_log.png", plot = prior_plot_2)
ggsave(filename = "figures/prior_plot_betagamble.png", plot = prior_plot_3)
ggsave(filename = "figures/prior_plot_betagamble_log.png", plot = prior_plot_4)
```

```{r prior posterior prediction checks}
print(draws_df)

prior_preds <- numeric(trials)

for (i in 1:trials){
  prior_preds[i] <- mean(draws_df[[125+i]])
}

posterior_preds <- numeric(trials)

for (i in 1:trials){
  posterior_preds[i] <- mean(draws_df[[245+i]])
}

# Prior predictions
predictions_prior_plot <- ggplot() +
  geom_histogram(aes(prior_preds), color = "darkblue", fill = "blue", alpha = 0.3, binwidth = 0.002) +
  xlab("The predicted proportion of choosing the right hand out of 120 trials") +
  ylab("Counts") +
  theme_classic()

# Posterior predictions
predictions_posterior_plot <- ggplot() +
  geom_histogram(aes(posterior_preds), color = "darkblue", fill = "blue", alpha = 0.3, binwidth = 0.002) +
  #geom_vline(x = mean(data$choice)) +
  # #geom_point(x = mean(data$choice), y = 0, color = "red", shape = 17, size = 5) +
  xlab("The predicted proportion of choosing the right hand out of 120 trials") +
  ylab("Counts") +
  theme_classic()

predictions_prior_plot
predictions_posterior_plot

ggsave(filename = "figures/prior_predictions.png", plot = predictions_prior_plot)
ggsave(filename = "figures/posterior_predictions.png", plot = predictions_posterior_plot)
```

```{r model quality}
# Model quality check

samples$cmdstan_diagnose()

diagnostics_caterpillar_plot <- ggplot(draws_df, aes(.iteration, rate, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()

ggsave(filename = "figures/caterpillar.png", plot = diagnostics_caterpillar_plot)
```

```{r parameter recovery}
# Parameter recovery

# Now we need to scale it up to all possible rates and noises
recovery_df <- NULL

for (noiseLvl in seq(0, 0.5, 0.1)) { # Looping through noise levels
  for (rateLvl in c(-5,-3,-1,-0.5,0,0.5,1,3,5)) { # Looping through rate levels
    for (beta_g in c(-10,-5,-1,-0.5,0,0.5,1,5,10)) {
      for (n_trials in c(12,120,1200)) {
        # Generate list of choices
        outcome <- WinLoseResults_model_f(n_trials, noiseLvl, rateLvl, betagamble = beta_g)
      
        # Create data for model
        data <- list(
          trials = n_trials,
          success = outcome$feedback,
          choice = outcome$choice
        )
        
        samples <- portfolio2_model$sample(
          data = data,
          #seed = 123,
          chains = 1,
          parallel_chains = 1,
          threads_per_chain = 1,
          iter_warmup = 1000,
          iter_sampling = 2000,
          refresh = 0,
          max_treedepth = 20,
          adapt_delta = 0.99,
        )
        
        draws_df <- as_draws_df(samples$draws()) 
        temp <- tibble(rate_est = mean(inv_logit_scaled(draws_df$rate)), 
                       rate_true = rateLvl,
                       beta_g_est = mean(inv_logit_scaled(draws_df$betaGamble)),
                       beta_g_true = beta_g,
                       noise = noiseLvl,
                       trials = n_trials)
        
        
        if (exists("recovery_df")) {recovery_df <- rbind(recovery_df, temp)} else {recovery_df <- temp}
      }
    }
  }
}

write_csv(recovery_df, "simdata/W3_recoverydf_alternative_trials.csv")
```


```{r visualising pr}
recovery_df <- read_csv("simdata/W3_recoverydf_alternative_trials.csv")

param_recov_rate_12 <- recovery_df %>% 
  filter(trials == 12) %>% 
  ggplot(aes(rate_est, inv_logit_scaled(rate_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw() +
  labs(x = "Estimated Rate", y = "True Rate", title = "Parameter Recovery For Different Levels of Noise: Rate", subtitle = "For 12 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_betag_12 <- recovery_df %>% 
  filter(trials == 12) %>% 
  ggplot(aes(beta_g_est, inv_logit_scaled(beta_g_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw()+
  labs(x = "Estimated BetaGamble", y = "True BetaGamble", title = "Parameter Recovery For Different Levels of Noise: BetaGamble", subtitle = "For 12 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_rate_120 <- recovery_df %>% 
  filter(trials == 120) %>% 
  ggplot(aes(rate_est, inv_logit_scaled(rate_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw() +
  labs(x = "Estimated Rate", y = "True Rate", title = "Parameter Recovery For Different Levels of Noise: Rate", subtitle = "For 120 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_betag_120 <- recovery_df %>% 
  filter(trials == 120) %>% 
  ggplot(aes(beta_g_est, inv_logit_scaled(beta_g_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw()+
  labs(x = "Estimated BetaGamble", y = "True BetaGamble", title = "Parameter Recovery For Different Levels of Noise: BetaGamble", subtitle = "For 120 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_rate_1200 <- recovery_df %>% 
  filter(trials == 1200) %>% 
  ggplot(aes(rate_est, inv_logit_scaled(rate_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw() +
  labs(x = "Estimated Rate", y = "True Rate", title = "Parameter Recovery For Different Levels of Noise: Rate", subtitle = "For 1200 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_betag_1200 <- recovery_df %>% 
  filter(trials == 1200) %>% 
  ggplot(aes(beta_g_est, inv_logit_scaled(beta_g_true))) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  geom_abline(intercept = 0,slope=1)+
  facet_wrap(.~noise) +
  theme_bw()+
  labs(x = "Estimated BetaGamble", y = "True BetaGamble", title = "Parameter Recovery For Different Levels of Noise: BetaGamble", subtitle = "For 1200 trials") +
  lims(x = c(0,1), y = c(0,1))

param_recov_rate_12
param_recov_rate_120
param_recov_rate_1200
param_recov_betag_12
param_recov_betag_120
param_recov_betag_1200

ggsave(filename = "figures/param_recov_rate_12.png", plot = param_recov_rate_12)
ggsave(filename = "figures/param_recov_rate_120.png", plot = param_recov_rate_120)
ggsave(filename = "figures/param_recov_rate_1200.png", plot = param_recov_rate_1200)
ggsave(filename = "figures/param_recov_betagamble_12.png", plot = param_recov_betag_12)
ggsave(filename = "figures/param_recov_betagamble_120.png", plot = param_recov_betag_120)
ggsave(filename = "figures/param_recov_betagamble_1200.png", plot = param_recov_betag_1200)
```

